name: Run tests

on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Pull submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          sudo apt-get install libprotobuf-c-dev
      - name: Build Substrait planloader library
        run: |
          cd ${{ github.workspace }}/third_party/substrait-cpp
          make release
      - name: Install Substrait planloader library
        run: |
          cd ${{ github.workspace }}/third_party/substrait-cpp/build-Release/export/planloader
          make install
      - name: Install package and test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[test]"
      - name: Run tests
        run: |
          python -m pytest
